# Generated by Django 3.1 on 2021-12-13 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Уровни иерархии',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('employment_date', models.DateField()),
                ('salary', models.PositiveIntegerField(blank=True)),
                ('total_salary', models.PositiveIntegerField(null=True)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_boss_id', to='Firm_structure.head')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Firm_structure.levels')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_position', to='Firm_structure.position')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
