# Generated by Django 3.1 on 2021-12-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firm_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
    ]
