# Generated by Django 3.1 on 2021-12-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firm_structure', '0002_remove_employees_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name_plural': 'Уровни доступа'},
        ),
        migrations.RemoveField(
            model_name='head',
            name='boss_id',
        ),
    ]
