# Generated by Django 3.1 on 2021-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firm_structure', '0003_auto_20211214_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='boss_id',
            new_name='boss_name',
        ),
    ]
