# Generated by Django 3.1 on 2021-12-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firm_structure', '0004_auto_20211214_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='boss_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_boss_name', to='Firm_structure.head'),
        ),
    ]
