# Generated by Django 3.1 on 2021-12-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firm_structure', '0005_auto_20211214_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='boss_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='boss_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_boss_id', to='Firm_structure.head'),
        ),
        migrations.AddField(
            model_name='head',
            name='boss_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
