# Generated by Django 3.1 on 2021-12-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firm_structure', '0006_auto_20211214_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='boss_id',
        ),
        migrations.RemoveField(
            model_name='head',
            name='boss_id',
        ),
        migrations.AddField(
            model_name='employees',
            name='head_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_head_name', to='Firm_structure.head'),
        ),
    ]
